name: EasyKeep
version: 1.0.0
api: [1.12.0]
main: EasyKeep\Main
commands:
  ek:
    usage: /ek <on | off>
    description: Enabled or disables EasyKeep
    permission: easykeep.enable
permissions:
  easykeep:
    default: false
    description: Gives the player all access to EasyKeep
    children:
      easykeep.enable:
        default: op
        description: Allows the player to disable/enable EasyKeep
      easykeep.keep:
        default: true
        description: Allows the player to keep their inventory when they die
