name: EasyKeep
main: EasyKeep\Main
version: 1.0.0
api: [1.12.0]
commands:
  ek:
    usage: /ek <on | off> [all]
    description: Enabled/Disabled EasyKeep
    permission: ek.toggle
permissions:
  ek:
    default: false
    description: Allows the user to use all of the EasyKeep features
    children:
      ek.toggle:
        default: true
        description: Allows the user to toggle EasyKeep for themselves
        children:
          ek.toggle.all:
            default: op
            description: Allows the player to toggle EasyKeep for the entire server
